version: '3'
services:
  backend:
    build: .
    volumes:
      - ./reports:/app/reports
    ports:
      - "8000:8000"
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    command: ["npm","run","dev"]
    ports:
      - "5173:5173"
